---
title: Qui êtes-vous ?
choices:
- label: Particulier
  id: particulier
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "Problème technique dans l'utilisation de data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Faire un retour sur la plateforme"
      id: retour-plateforme
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Demande relative à l'ouverture des données publiques"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Question sur des données géographiques"
      id: geo
      link:
        form:
          title: Contactez-nous
          recipient: geo@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
- label: Chercheur ou journaliste 
  id: chercheur
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "Problème technique dans l'utilisation de data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Faire un retour sur la plateforme"
      id: retour-plateforme
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Demande relative à l'ouverture des données publiques"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Question sur des données géographiques"
      id: geo
      link:
        form:
          title: Contactez-nous
          recipient: geo@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
- label: Administration centrale
  id: administration-centrale
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "Problème technique dans l'utilisation de data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Faire un retour sur la plateforme"
      id: retour-plateforme
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Demande relative à l'ouverture des données publiques"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Référencer mes données sur data.gouv.fr"
      id: referencement
      link:
        title: 'Où sont situées vos données ?'
        choices:
        - label: Mes données sont sur un portail open data existant
          id: moissonnage
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: moissonnage@data.gouv.fr
        - label: Mes données ne sont pas sur un portail open data existant
          id: ouverture
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: ouverture@data.gouv.fr
    - label: "Faire une demande d'homologation de licence"
      id: licence
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: homologation.licence@data.gouv.fr
    - label: "Faire certifier mon organisation sur data.gouv.fr"
      id: certification
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: certification@data.gouv.fr
    - label: "Question sur des données géographiques"
      id: geo
      link:
        form:
          title: Contactez-nous
          recipient: geo@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
- label: Collectivité territoriale
  id: collectivite-territoriale
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "Problème technique dans l'utilisation de data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Faire un retour sur la plateforme"
      id: retour-plateforme
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Demande relative à l'ouverture des données publiques"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Référencer mes données sur data.gouv.fr"
      id: referencement
      link:
        title: 'Où sont situées vos données ?'
        choices:
        - label: Mes données sont sur un portail open data existant
          id: moissonnage
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: moissonnage@data.gouv.fr
        - label: Mes données ne sont pas sur un portail open data existant
          id: ouverture
          link:
            form:
              title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
              recipient: ouverture@data.gouv.fr
    - label: "Faire une demande d'homologation de licence"
      id: licence
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: homologation.licence@data.gouv.fr
    - label: "Faire certifier mon organisation sur data.gouv.fr"
      id: certification
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: certification@data.gouv.fr
    - label: "Question sur des données géographiques"
      id: geo
      link:
        form:
          title: Contactez-nous
          recipient: geo@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
- label: Entreprise
  id: entreprise
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "Problème technique dans l'utilisation de data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Faire un retour sur la plateforme"
      id: retour-plateforme
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Demande relative à l'ouverture des données publiques"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Question sur des données géographiques"
      id: geo
      link:
        form:
          title: Contactez-nous
          recipient: geo@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
- label: Association
  id: association
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "Problème technique dans l'utilisation de data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Faire un retour sur la plateforme"
      id: retour-plateforme
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Demande relative à l'ouverture des données publiques"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Question sur des données géographiques"
      id: geo
      link:
        form:
          title: Contactez-nous
          recipient: geo@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
- label: Autre
  id: autre
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "Problème technique dans l'utilisation de data.gouv.fr"
      id: probleme-technique
      link:
        form:
          title: Contactez-nous (nous vous invitons à consulter la documentation au préalable)
          recipient: support@data.gouv.fr
    - label: "Signaler une faille de sécurité"
      id: faille-securite
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Faire un retour sur la plateforme"
      id: retour-plateforme
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr
    - label: "Demande relative à l'ouverture des données publiques"
      id: ouverture-donnees-publiques
      link:
        form:
          title: Contactez-nous (cette demande d'information n'est pas assimilable à une saisie CADA)
          recipient: ouverture@data.gouv.fr
    - label: "Question sur des données géographiques"
      id: geo
      link:
        form:
          title: Contactez-nous
          recipient: geo@data.gouv.fr
    - label: "Autre"
      id: autre
      link:
        form:
          title: Contactez-nous
          recipient: support@data.gouv.fr