---
title: Qui êtes-vous ?
choices:
- label: Un testeur de cet outil de support
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: Je veux tester le formulaire de contact
      link:
        form:
          title: Contactez-nous
          recipient: test@data.gouv.fr
    - label: Je veux tester le formulaire de contact quand Zammad ne marche pas
      link:
        form:
          title: Contactez-nous (mais ça ne va pas marcher haha)
          recipient: croute@data.gouv.fr
    - label: Je veux tester une sous-question
      link:
        title: 'Vous voulez tester :'
        choices:
        - label: Du contenu en markdown
          link:
            path: answers/contenu.md
        - label: Du contenu brut
          link:
            content: Le contenu brut se configure directement dans le fichier config/question-tree.yaml
- label: Un particulier
  link:
    title: Comment pouvons-nous vous aider ?
    choices:
    - label: "J'ai une question sur une procédure administrative"
      link:
        path: answers/demarches_admin.md
    - label: "J'ai constaté une erreur ou j'ai une question relative à un jeu de donnée publié sur data.gouv.fr"
      link:
        path: question_donnees.md
    - label: "J'ai un problème technique dans l'utilisation de la plateforme data.gouv.fr"
      link:
        form:
          title: "Contactez-nous (nous vous invitions à consulter la [documentation](https://doc.data.gouv.fr/) au préalable".
           recipient: support@data.gouv.fr
     - label: "J'ai une demande relative à l'ouverture des données publiques : données absentes ou difficiles à trouver"
       link:
        form:
          title: "Contactez-nous (Cette demande d'information n'est pas assimilable à une saisie de la Commission d'accès aux documents administratifs (CADA))".
           recipient: ouverture@data.gouv.fr  
    - label: "J'ai une question relative à des données à caractère personnel"
      link:
        title: 'Votre question concerne :'
        choices:
        - label: La base de données des demandes de valeurs foncières (transactions immobilières)
          link:
            content: La réponse est non
        - label: Le Repertoire national des associations (RNA)
          link:
            content: La réponse est toujours non        
        - label: La base Sirene des entreprises et de leurs établissements (SIREN, SIRET)
          link:
            content: "Puisqu'on vous dit que c'est non"  
        - label: Le fichier des personnes décédées
          link:
            content: Bon très bien, les réponses à ces questions sont [ici](https://pad.incubateur.net/Su0HeDybQzSKV1wQ3Vn0Uw?both)  
